### ISSUE TITLE
api response is not return 

### ISSUE THREAD

**Issue by nixecn** [FaNathan/Angular-DropZone#3]
Thank you so much for the component you developed. but ,my api return file info after uploaded file  .so can you provide the interface to return upload api 's response ,

**Comment by FaNathan** [comment]
Hi @leehonleon. Good point. 

`<dropzone-advanced (uploaded)="yourFunction($event)"></dropzone-advanced>
`"uploaded" event can return the status of all files. this is not enough? by the way, it can return api response too. I'll have a look

**Comment by FaNathan** [comment]
![Screenshot 2022-05-07 205918](https://user-images.githubusercontent.com/102886270/167252554-ffb39221-f4af-45a6-860e-f78ce35efa10.png)


Just updated the model. 
i.e. you need to send the responseType on making API ( **"json"** here ). it can be `"blob" | "arraybuffer" | "text" | "json" | undefined`. Default value is blob.

` const uploadApi = new AngularDropzoneAPI('http://localhost:5000/FileUpload/UploadLargeFile', 'POST', undefined, undefined, "json");
`

**Comment by nixecn** [comment]
thank your very  much.  the apiResponse is exactly what I want.

**Comment by nixecn** [comment]
it is wery good for resolve my problem. thank you. dear FaNathan
