### ISSUE TITLE
why used http.request send OPTIONS request?

### ISSUE THREAD

**Issue by nixecn** [FaNathan/Angular-DropZone#5]
I clone the source and run it . why it send the OPTIONS request to my server. 
but when  i use [npm install angular-dropzone] install package to my project , it send POST request to my server?

When it send the OPTIONS request , i well must provide that api . What can i do in this api?

**Comment by FaNathan** [comment]
Hi @leehonleon 
I'm afraid that I might have misunderstood what you mean. you don't wanna send options?  just send undefined or null to the api constructor.
` const uploadApi = new AngularDropzoneAPI('http://lupload_url', 'POST', undefined, undefined, "json");`
